{
 "title": "Kafka-Zookeeper-Flink-dashboard",
 "description": "Flink Metrics for skewed data and CPU intensive processing",
 "time": { "from": "now-25m", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   },
   {
    "name": "Zookeeper",
    "label": "Kafka Zookeeper",
    "query": "label_values(zookeeper_InitLimit,instance)"
   },
   {
    "name": "Flink_Job_Name",
    "query": "label_values(flink_jobmanager_job_uptime,job_name)"
   },
   {
    "name": "Source",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Sink",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pods",
    "query": "label_values(kube_pod_container_info,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelections_total)"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(zookeeper_quorumsize)" }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_outstandingrequests", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount)"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "singlestat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount)"
    }
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency",
     "legendFormat": "{{instance}}-replica[{{replicaId}}]"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency",
     "legendFormat": "{{instance}}-replica[{{replicaId}}]"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency",
     "legendFormat": "{{instance}}-replica[{{replicaId}}]"
    }
   ]
  },
  { "title": "Flink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Task slots",
   "type": "singlestat",
   "description": "Total number of task slots on the Flink cluster",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal",
     "legendFormat": "Total task slots"
    }
   ]
  },
  {
   "title": "Available task slots",
   "type": "singlestat",
   "description": "Available tasks slots on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "singlestat",
   "description": "The total number of Task Managers (TM) on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "description": "The total number of running jobs on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "Running Jobs"
    }
   ]
  },
  {
   "title": "Job's elapsed time running",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "flink_jobmanager_job_uptime", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Thread counter on Task Manager's",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Number of threads" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU LOAD - Job/Task Managers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "JobManager ({{host}})"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "TaskManager ({{host}})"
    }
   ]
  },
  {
   "title": "Job Manager memory",
   "type": "graph",
   "description": "Memory total and available at the Job Manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decgbytes", "label": "Giga bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_Memory_Total",
     "legendFormat": "{{host}} - Total"
    },
    {
     "expr": "flink_jobmanager_System_Memory_Available",
     "legendFormat": "{{host}} - Available"
    }
   ]
  },
  {
   "title": "Task Manager memory",
   "type": "graph",
   "description": "Memory total and available at the Task Managers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decgbytes", "label": "Giga bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_Memory_Total",
     "legendFormat": "{{host}} - Total"
    },
    {
     "expr": "flink_taskmanager_System_Memory_Available",
     "legendFormat": "{{host}} - Available"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time",
     "legendFormat": "{{host}} Young Gen Time"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time",
     "legendFormat": "{{host}} Old Gen Time"
    }
   ]
  },
  {
   "title": "JobManager and TaskManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "JobManager ({{host}}) Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "JobManager ({{host}}) Available"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "TaskManager ({{host}}) Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "TaskManager ({{host}}) Available"
    }
   ]
  },
  {
   "title": "JobManager and TaskManager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "decbytes", "label": "MBytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "Job Manager ({{host}}) memory used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
     "legendFormat": "Job Manager ({{host}}) memory available"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "Task Manager ({{host}}) memory used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity",
     "legendFormat": "Task Manager ({{host}}) memory available"
    }
   ]
  },
  {
   "title": "MemorySegments at TaskManager's",
   "type": "graph",
   "description": "MemorySegments at TaskManager's",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments",
     "legendFormat": "{{host}} - AvailableMemorySegments (shuffle netty)"
    },
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments",
     "legendFormat": "{{host}} - TotalMemorySegments (shuffle netty)"
    }
   ]
  },
  {
   "title": "records/sec IN of each operator by Task Manager",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Number of Records/sec" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond",
     "legendFormat": "{{host}}-{{task_name}}"
    }
   ]
  },
  {
   "title": "records/sec OUT of each operator by Task Manager",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Number of Records/sec" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
     "legendFormat": "{{host}}-{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes/sec IN of each operator by Task Manager",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond",
     "legendFormat": "{{host}}-{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes/sec OUT of each operator by Task Manager",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond",
     "legendFormat": "{{host}}-{{task_name}}"
    }
   ]
  }
 ]
}